
spring:
  application:
    name: cadastro-api
    
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true